config/routes.rb
Rails.application.routes.draw do
  resources :tasks

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :borders do
    collection do
      get 'about'
      get 'howto'
    end
  end
  root 'borders#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/border.rb
class Border < ApplicationRecord
    belongs_to :user
end

app/controllers/borders_controller.rb
class BordersController < ApplicationController
  before_action :authenticate_user!, only: [:new]
  before_action :set_border, only: [:show, :edit, :update, :destroy]
  def index
    @border = Border.all
  end

  def show
  end

  def edit
  end

  def new
    @border = Border.new
  end

  def create
    @border = Border.new(border_params)
    @border.user_id = current_user.id
    if @border.save
      redirect_to root_path, notice: '作成できました'
    else
      render :new, alert: '作成できませんでした'
    end
  end

  def update
    if @border.update(border_params)
      redirect_to @border, notice: '更新できました'
    else
      render :show, alert: '更新できませんでした'
    end
  end

  def destroy
    if @border.destroy
      redirect_to root_path, notice: '削除しました'
    else
      redirect_to root_path, alert: '削除に失敗しました'
    end
  end

  def about
  end

  private
    def set_border
      @border = Border.find(params[:id])
    end

    def border_params
      params.require(:border).permit(:memo, :subject, :content, :deadline)
    end
end

app/helpers/borders_helper.rb
module BordersHelper
end

app/views/borders/_form.html.erb
<div class = "container">
    <%= form_for(@border) do |f| %>
        <div class = "card container pt-3">
            <div class = "form-group">
                <%= f.label '教科'%>
                <%= f.select :subject, ['電子工学','微分積分','応用物理','現代社会','英語','電気回路','実験実習','ディジタル回路',
                                        '電磁気学','コミュニケーション','エネルギー変換工学','英語コミュニケーション'], class: 'form-control'%>
            </div>

            <div class = "form-group">
                <%= f.label '課題内容'%>
                <%= f.text_field :content, class: 'form-control'%>
            </div>

            <div class = "form-group">
                <%= f.label '締め切り'%>
                <%= f.date_select :deadline, use_month_numbers:true, prompt:"--", class: 'form-control'%>
            </div>

            <div class = "form-group">
                <%= f.label 'メモ'%>
                <%= f.text_area :memo, class: 'form-control'%>
            </div>
            
        </div>

        <%= f.submit "課題登録", class:'btn btn-success float-right mt-3'%>
    <%end%>
</div>

app/views/borders/about.html.erb
<div class="card">
    <div class="card-header font-weight-bold text-center">利用規約　※読んでね！</div>
    <div class="card-body">
        <ul>
            <li>このサイトは一個人による自己満＆web制作の勉強のために作っています</li>
            <li>スマホでも動くと思いますがPC推奨です</li>
            <li>このサイトは誰でも編集することのできるサイトですので荒らさないでください。
            開発者の技量不足で今の所対策が取れないので荒らしがあったら閉鎖します</li>
            <li>個人用として使えるようログイン機能も設けたいと思いますのでいましばらくお待ち下さい。</li>
            <li>このサイトに欲しい機能などありましたら　<br> Twitter -> @mkrms_again のDMにお願いします(鍵垢です)</li>
        </ul>
    </div>
</div>

app/views/borders/howto.html.erb
<div class ="container">
<div class="card">
    <div class="card-header font-weight-bold text-center">使い方</div>
    <div class="card-body">
        <p class = "">
            <h3>課題登録機能の使い方</h3>
            １．新規作成を押す（ユーザー登録が必要です）<br>
            ２．教科、課題内容、締切、メモ欄を入力<br>
            ３．課題登録ボタンで登録（学籍番号が表示されます）<br>
            Topページの詳細リンクから、詳細を閲覧可能<br>
        </p>

        <p>
            <h3>Todoの使い方</h3>
            １．新規作成を押す（ユーザー登録が必要です）<br>
            ２．タイトルと内容を入力<br>
            他のユーザーには見られません<br>
        </p>
    </div>
</div>
</div>

app/views/borders/index.html.erb
<div class ="container-fluid">
    <h2 class ="text-center">[課題管理]</h2>
    <div class="row justify-content-around">
        <div class = "d-inline-block col">
            <%= link_to "新規作成", new_border_path, class: "btn btn-primary mb-3" %>
            <table class = "table table-bordered">
                <thead class = "thead-light">
                    <tr>
                        <th>教科</th>
                        <th>課題内容</th>
                        <th>締め切り</th>
                        <th>作成者</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <% @border.each do |border| %>
                        <tr>
                            <td><%= border.subject %></td>
                            <td><%= border.content %></td>
                            <% if border.deadline.present?%>
                        <% if Date.today < border.deadline %>
                            <td> <%= border.deadline%> </td>
                        <%elsif Date.today > border.deadline %>
                            <td class ="text-danger"> <%= border.deadline %> </td>
                        <% else %>
                            <td class = "text-success"> <%= border.deadline %> </td>
                        <% end %>

                        <% else %>
                        <td></td>
                        <%end%>
                            <td><%= border.user.name %></td>
                            <td><%= link_to '詳細',  border %></td>
                        </tr>
                    <% end %>

                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/borders/new.html.erb
<%= render 'form' %>

app/views/borders/show.html.erb
<div class = "container">
    <div class="card">
        <div class="card-header">
            <%= @border.subject %><p class ="text-center font-weight-bold">課題内容：<%= @border.content %></p>
        </div>

        <div class="card-body">
            <div class = "font-weight-bold">メモ</div><p class ="container"><%= @border.memo %></p>
        </div>
        <div class="card-footer">
            <div class = "float-right"><%= @border.deadline%></div>
        </div>
    </div>

    <%= link_to "削除", border_path(@border), method: :delete, data: {confirm: "本当に削除しますか？"}, class: 'btn btn-danger float-right mt-3'%>
</div>