config/routes.rb
Rails.application.routes.draw do
  resources :tasks

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :borders do
    collection do
      get 'about'
      get 'howto'
    end
  end
  root 'borders#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :validate_user, only: [:show, :edit, :update, :destroy]

  def index
    @task = current_user.tasks.all
  end

  def show
  end

  def edit
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id
    if @task.save
      redirect_to root_path, notice: '作成できました'
    else
      render :new, alert: '作成できませんでした'
    end
  end

  def update
    if @task.update(task_params)
      redirect_to root_path, notice: '更新できました'
    else
      render :show, alert: '更新できませんでした'
    end
  end

  def destroy
    if @task.destroy
      redirect_to root_path, notice: '削除しました'
    else
      redirect_to root_path, alert: '削除に失敗しました'
    end
  end

  def about
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:title, :body)
    end

    def validate_user
      if @task.user != current_user
        redirect_to root_path, alert: "自分のタスクではありません"
      end
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>

app/views/tasks/index.html.erb
<% if user_signed_in? %>
<h2 class ="text-center">[Todoリスト]</h2>
        <div class ="d-inline-block col align-self-center">
        <div class ="d-inline-block col align-self-center">
    <%= link_to "新規作成", new_task_path, class: "btn btn-primary" %>
<table class = "table table-bordered">
    <thead class = "thead-light">
        <tr>
            <th>タイトル</th>
            <th>内容</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @task.each do |task| %>
            <tr>
                <td><%= task.title %></td>
                <td><%= task.body %></td>
                <td><%= link_to '詳細',  task %></td>
            </tr>
        <% end %>
    </tbody>
</table>
        </div>
        <% end %>

app/views/tasks/new.html.erb
<div class = "container">
    <%= form_for(@task) do |f| %>
        <div class = "card container pt-3">
            <div class = "form-group">
                <%= f.label 'タイトル'%>
                <%= f.text_field :title, class: 'form-control'%>
            </div>

            <div class = "form-group">
                <%= f.label '内容'%>
                <%= f.text_field :body, class: 'form-control'%>
            </div>
            
        </div>

        <%= f.submit "タスク登録",class:'btn btn-success float-right mt-3'%>
    <%end%>
</div>

app/views/tasks/show.html.erb
<div class = "container">
    <div class="card">
        <div class="card-header">
            <p class ="text-center font-weight-bold">タイトル：<%= @task.title %></p>
        </div>

        <div class="card-body">
            <div class = "font-weight-bold">メモ</div><p class ="container"><%= @task.body%></p>
        </div>
        <div class="card-footer">
        </div>
    </div>

    <%= link_to "削除", task_path(@task), method: :delete, data: {confirm: "本当に削除しますか？"}, class: 'btn btn-danger float-right mt-3'%>
</div>