config/routes.rb
Rails.application.routes.draw do
  resources :tasks

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :borders do
    collection do
      get 'about'
      get 'howto'
    end
  end
  root 'borders#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManagementForKosen</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-2">
      <a href="/" class="navbar-brand"> E3 Management</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="ナビゲーションの切替">
      <span class="navbar-toggler-icon"></span>
    </button>

        <div class="collapse navbar-collapse" id="navbar">
      <ul class="navbar-nav mr-auto ml-5">
        <li class="nav-item">
          <%= link_to 'Topに戻る', root_path, class: 'text-white pr-3'%>
        </li>
        <li class="nav-item">
          <%= link_to 'Todo', tasks_path, class: 'text-white pr-3'%>
        </li>
        <li class="nav-item">
          <%= link_to '利用規約', about_borders_path, class: 'text-white pr-3'%>
        </li>
        <li class="nav-item">
          <%= link_to '使い方', howto_borders_path, class: 'text-white pr-3'%>
        </li>
      </ul>

        <div class = "float-right">
            <% if user_signed_in? %>
                <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'btn btn-success mr-3' %>
            <% else %>
                <%= link_to 'サインアップ', new_user_registration_path, class: 'btn btn-primary mr-3' %>
                <%= link_to 'ログイン', new_user_session_path, class: 'btn btn-success mr-3' %>
            <% end %>
        </div>
    </nav>
    
    <%= yield %>
  </body>
</html>